pub mod build_info;
pub mod claude_install;
pub mod codex_install;
pub mod codex_trust;
pub mod context;
pub mod conversation;
pub mod daemon;
pub mod delivery;
pub mod error;
pub mod filewatch;
pub mod identity;
pub mod ipc;
pub mod paths;
pub mod pi_install;
pub mod pidfile;
pub mod profiles;
pub mod routing;
pub mod state;
pub mod terminal;
pub mod unix;
pub mod watcher;

pub use error::{EyesError, Result};
